name: test_github_actions
on: [push]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            extension: bat
            name: windows-blender293
            python: 3.9
          - os: ubuntu-latest
            extension: sh
            name: linux-blender293
            python: 3.9
          - os: macos-latest
            extension: osx
            name: macOS-blender293
            python: 3.9
          - os: windows-latest
            extension: bat
            name: windows-blender31
            python: 3.9
          - os: ubuntu-latest
            extension: sh
            name: linux-blender31
            python: 3.9
          - os: macos-latest
            extension: osx
            name: macOS-blender31
            python: 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: build
        run: ./build_mtree.${{ matrix.extension }}
      - name: package addon
        run: python .github/scripts/setup_addon.py
      - name: upload zipped addon
        uses: actions/upload-artifact@v2
        with:
          name: modular_tree_${{ matrix.name }}
          path: tmp/*.zip
  
  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      STATUS: ${{ !endsWith(github.ref, 'master') && 'alpha' || '' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat VERSION)
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./modular_tree_windows-blender293/modular_tree_${{ steps.vars.outputs.version }}_windows_blender293-30.zip ./modular_tree_windows-blender31/modular_tree_${{ steps.vars.outputs.version }}_windows_blender31.zip ./modular_tree_linux-blender293/modular_tree_${{ steps.vars.outputs.version }}_linux_blender293-30.zip ./modular_tree_linux-blender31/modular_tree_${{ steps.vars.outputs.version }}_linux_blender31.zip ./modular_tree_macOS-blender293/modular_tree_${{ steps.vars.outputs.version }}_macOS_blender293-30.zip ./modular_tree_macOS-blender31/modular_tree_${{ steps.vars.outputs.version }}_macOS_blender31.zip
          release: Release V${{ steps.vars.outputs.version }}${{ env.STATUS }}
          tag: ${{ steps.vars.outputs.version }}${{ env.STATUS }}
          message: V${{ steps.vars.outputs.version }}
          body: ''

